// SPDX-License-Identifier: Apache-2.0

package theme

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"strings"
)

// A theme writes into files the project already owns (theme/web/main.scss is
// three lines of Mendix's own, custom-variables.scss carries Atlas's defaults),
// so it can never rewrite a whole file. Instead each write is fenced between
// markers and only the fenced region is ever replaced — the guard-don't-drop
// rule from ADR-0005, applied to files instead of BSON.
//
// The end marker carries a digest of the body that was written. On re-apply the
// digest is recomputed from what is on disk: equal means mxcli's own output is
// still there and may be replaced, different means a human edited inside the
// fence and the write is refused unless forced. That keeps the record in the
// file itself — no sidecar state to drift out of sync with the project.
const (
	beginMarker = "mxcli:theme:begin"
	endMarker   = "mxcli:theme:end"
)

// Action is what applying one file did.
type Action string

const (
	// ActionCreated means the file did not exist and was written.
	ActionCreated Action = "created"
	// ActionAdded means the file existed without a block and the block was appended.
	ActionAdded Action = "added"
	// ActionUpdated means an existing, unmodified block was replaced.
	ActionUpdated Action = "updated"
	// ActionUnchanged means the block on disk already matches what would be written.
	ActionUnchanged Action = "unchanged"
	// ActionRemoved means the block (and its trailing blank line) was cut out.
	ActionRemoved Action = "removed"
	// ActionSkipped means a hand-edited block was left alone.
	ActionSkipped Action = "skipped"
)

// ErrBlockModified reports a fenced block whose contents no longer match the
// digest mxcli recorded, i.e. someone edited inside the fence.
type ErrBlockModified struct {
	Theme string
	Path  string
}

func (e *ErrBlockModified) Error() string {
	return fmt.Sprintf("%s: the '%s' block has local edits, so it was left alone\n"+
		"  keep them: move your lines outside the mxcli:theme markers\n"+
		"  discard them: re-run with --force", e.Path, e.Theme)
}

// digest is the short content hash recorded in the end marker.
func digest(body string) string {
	sum := sha256.Sum256([]byte(body))
	return hex.EncodeToString(sum[:])[:16]
}

// commentSyntax returns the line-comment prefix for a file the theme writes.
// Only SCSS/CSS/JS carry blocks today and all three use "//"; anything else is
// copied verbatim and never reaches this function.
func commentSyntax() string { return "//" }

func beginLine(name, version string) string {
	return fmt.Sprintf("%s %s %s v%s — generated by `mxcli theme apply`; edit outside this block",
		commentSyntax(), beginMarker, name, version)
}

func endLine(name, body string) string {
	return fmt.Sprintf("%s %s %s %s", commentSyntax(), endMarker, name, digest(body))
}

// block is a fenced region located inside a file.
type block struct {
	// start and end are line indices: start is the begin marker, end the end marker.
	start, end int
	// body is everything between the markers, without a trailing newline.
	body string
	// recorded is the digest the end marker claims the body has.
	recorded string
}

// findBlock locates the fenced region for a theme. found is false when the file
// carries no block for that theme.
func findBlock(content, name string) (b block, found bool) {
	lines := strings.Split(content, "\n")
	beginNeedle := beginMarker + " " + name + " "
	endNeedle := endMarker + " " + name + " "

	b.start, b.end = -1, -1
	for i, line := range lines {
		switch {
		case b.start < 0 && strings.Contains(line, beginNeedle):
			b.start = i
		case b.start >= 0 && strings.Contains(line, endNeedle):
			b.end = i
			fields := strings.Fields(line)
			b.recorded = fields[len(fields)-1]
		}
		if b.end >= 0 {
			break
		}
	}
	if b.start < 0 || b.end < 0 {
		return block{}, false
	}
	b.body = strings.Join(lines[b.start+1:b.end], "\n")
	return b, true
}

// applyBlock returns the new file content with body fenced into existing.
//
// A block that is absent is appended; one that is present and untouched is
// replaced; one that a human has edited is refused unless force is set, because
// silently discarding someone's styling is exactly the failure this fencing
// exists to prevent.
func applyBlock(existing, name, version, body string, force bool) (string, Action, error) {
	body = strings.TrimRight(body, "\n")
	fenced := beginLine(name, version) + "\n" + body + "\n" + endLine(name, body)

	b, found := findBlock(existing, name)
	if !found {
		if strings.TrimSpace(existing) == "" {
			return fenced + "\n", ActionCreated, nil
		}
		return strings.TrimRight(existing, "\n") + "\n\n" + fenced + "\n", ActionAdded, nil
	}

	if b.recorded != digest(b.body) && !force {
		return existing, ActionSkipped, &ErrBlockModified{Theme: name, Path: ""}
	}
	if b.body == body {
		return existing, ActionUnchanged, nil
	}

	lines := strings.Split(existing, "\n")
	out := append([]string{}, lines[:b.start]...)
	out = append(out, strings.Split(fenced, "\n")...)
	out = append(out, lines[b.end+1:]...)
	return strings.Join(out, "\n"), ActionUpdated, nil
}

// removeBlock cuts a theme's fenced region back out of a file, leaving whatever
// the project had around it. A hand-edited block is kept unless force is set.
func removeBlock(existing, name string, force bool) (string, Action, error) {
	b, found := findBlock(existing, name)
	if !found {
		return existing, ActionUnchanged, nil
	}
	if b.recorded != digest(b.body) && !force {
		return existing, ActionSkipped, &ErrBlockModified{Theme: name, Path: ""}
	}

	lines := strings.Split(existing, "\n")
	out := append([]string{}, lines[:b.start]...)
	rest := lines[b.end+1:]
	// Drop the blank line applyBlock inserted before the fence, so repeated
	// apply/remove cycles do not accumulate whitespace.
	for len(out) > 0 && strings.TrimSpace(out[len(out)-1]) == "" {
		out = out[:len(out)-1]
	}
	for len(rest) > 0 && strings.TrimSpace(rest[0]) == "" {
		rest = rest[1:]
	}
	out = append(out, rest...)

	joined := strings.Join(out, "\n")
	if strings.TrimSpace(joined) == "" {
		return "", ActionRemoved, nil
	}
	return strings.TrimRight(joined, "\n") + "\n", ActionRemoved, nil
}
