// SPDX-License-Identifier: Apache-2.0

package theme

import (
	"fmt"
	"strings"
)

// SwitcherMDL returns the MDL that installs a runtime theme switcher into
// module.
//
// This is the one part of theming that cannot be files alone. A theme's
// light/dark blocks key off a class on the root element, and nothing in Mendix
// puts it there: Atlas ships the `:root.theme-dark` slot but no switcher, and
// there is no theme-level hook to run script before first paint —
// deployment/web/index.html is generated by mxbuild, and theme/web/settings.json
// only accepts cssFiles. So an explicit user choice has to come from the model:
// JavaScript actions the client can run, wrapped in nanoflows a button can call.
//
// The CSS still does the heavy lifting. `--variant auto` already renders the
// right palette before first paint by following the OS, so the switcher only
// has to handle the case where a user's stored choice differs from their OS
// preference — which is also the only case that can flash.
func SwitcherMDL(module string) string {
	return strings.ReplaceAll(switcherTemplate, "{{MODULE}}", module)
}

// SwitcherStorageKey is where an explicit choice is remembered in the browser.
const SwitcherStorageKey = "mxcli-theme"

const switcherTemplate = `-- Runtime theme switcher, installed by ` + "`mxcli theme switcher install`" + `.
--
-- The theme's SCSS already ships both palettes and follows the OS. These
-- actions exist for the one thing CSS cannot do: let a user override that
-- choice and have it remembered.
--
-- The class goes on <html> (":root"), so popups and modals — which Mendix
-- renders at <body>, outside any page container — follow it too.

-- Flip between light and dark, resolving "follow the OS" to whatever the OS is
-- currently saying, and remember the choice. Returns the theme now in force.
create or modify javascript action {{MODULE}}.ToggleAppTheme() returns String
exposed as 'Toggle app theme' in 'Theme'
as $$
var root = document.documentElement;
var effective;
if (root.classList.contains("theme-dark")) {
    effective = "dark";
} else if (root.classList.contains("theme-light")) {
    effective = "light";
} else {
    effective = window.matchMedia && window.matchMedia("(prefers-color-scheme: dark)").matches
        ? "dark"
        : "light";
}
var next = effective === "dark" ? "light" : "dark";
root.classList.remove("theme-light", "theme-dark");
root.classList.add("theme-" + next);
try {
    window.localStorage.setItem("mxcli-theme", next);
} catch (e) {
    // Private browsing and some embedded webviews reject storage; the class is
    // already applied, so the only thing lost is persistence across reloads.
}
return Promise.resolve(next);
$$;

-- Set the theme explicitly. Pass "auto" to drop the override and go back to
-- following the OS.
create or modify javascript action {{MODULE}}.SetAppTheme(
  Theme: String not null
) returns Boolean
exposed as 'Set app theme' in 'Theme'
as $$
var root = document.documentElement;
root.classList.remove("theme-light", "theme-dark");
try {
    if (Theme === "light" || Theme === "dark") {
        root.classList.add("theme-" + Theme);
        window.localStorage.setItem("mxcli-theme", Theme);
    } else {
        window.localStorage.removeItem("mxcli-theme");
    }
} catch (e) {
    if (Theme === "light" || Theme === "dark") {
        root.classList.add("theme-" + Theme);
    }
}
return Promise.resolve(true);
$$;

-- Re-apply a remembered choice. Nothing calls this automatically: Mendix pages
-- have no on-load event, and the usual substitute — a data view whose data
-- source is a nanoflow — is not something mxcli can author yet (the modelsdk
-- engine refuses a NanoflowSource data view, and the legacy engine writes one
-- with the nanoflow reference missing, which fails the build with "No nanoflow
-- configured for the data source of this data view"). Until that is closed,
-- wire it in Studio Pro if you want an explicit choice to survive a reload.
create or modify javascript action {{MODULE}}.ApplyStoredTheme() returns Boolean
exposed as 'Apply stored theme' in 'Theme'
as $$
var stored = null;
try {
    stored = window.localStorage.getItem("mxcli-theme");
} catch (e) {
    // No storage available: following the OS is the right fallback.
}
var root = document.documentElement;
root.classList.remove("theme-light", "theme-dark");
if (stored === "light" || stored === "dark") {
    root.classList.add("theme-" + stored);
}
return Promise.resolve(true);
$$;

-- Wire this to a button: actionbutton btnTheme (caption: 'Theme', action: nanoflow {{MODULE}}.ACT_ToggleTheme)
create or replace nanoflow {{MODULE}}.ACT_ToggleTheme()
returns String as $Theme
begin
  $Theme = call javascript action {{MODULE}}.ToggleAppTheme();
  return $Theme;
end;

-- Ready for whatever ends up calling it on load; nothing does today (see above).
create or replace nanoflow {{MODULE}}.ACT_ApplyStoredTheme()
returns Boolean as $Applied
begin
  $Applied = call javascript action {{MODULE}}.ApplyStoredTheme();
  return $Applied;
end;
`

// SwitcherNextSteps is printed after an install: the wiring mxcli does not do
// for the user, because it lands on a page or layout it did not create.
func SwitcherNextSteps(module string) string {
	return fmt.Sprintf(`Installed into %[1]s. One step left — add a toggle wherever it belongs,
typically a layout or a settings page:

    actionbutton btnTheme (caption: 'Theme', action: nanoflow %[1]s.ACT_ToggleTheme)

That is enough to switch: the click flips the palette and remembers the choice.

Reload behaviour: the app goes back to following the OS, because Mendix has no
page on-load event to re-apply the stored value from, and the usual substitute
(a data view with a nanoflow data source) is not authorable by mxcli yet on
either engine. %[1]s.ApplyStoredTheme is installed and ready for it — wire it in
Studio Pro if you need the choice to persist across reloads.`, module)
}
